### ISSUE TITLE
Cell numbers in labels.npz not same as cell_barcode_count.csv

### ISSUE THREAD

**Issue by vals** [weallen/STARmap#1]
Hi,

I want to investigate if STARmap data can be analyzed with out spatial methods.

These work by relating gene expression to spatial coordinates.

In all the data available at https://www.starmapresources.com/data/ there are more regions defined in the `labels.npz` file compared to the number of cells in the `cell_barcode_count.csv` file.

Here is a quick check I did:

```
for fname in glob('*/*/cell_barcode_count.csv'):
    counts = pd.read_csv(fname, header=-1)
    cells, genes = counts.shape
    
    labels_fname = fname.replace('cell_barcode_count.csv', 'labels.npz')
    labels = np.load(labels_fname)['labels']
    regions = len(regionprops(labels))
    
    rootname = fname.split('/')[1]
    
    print(f'{rootname}\t- Regions: {regions}\tCells: {cells}\tGenes: {genes}')

>
20171110_BF2_dark	- Regions: 1173	Cells: 1167	Genes: 160
20170915_BD2_dark	- Regions: 963	Cells: 941	Genes: 160
20171115_BF5_light	- Regions: 976	Cells: 975	Genes: 160
20171120_BF4_light	- Regions: 932	Cells: 931	Genes: 160
20180421_BZ19_cocaine	- Regions: 1327	Cells: 1320	Genes: 166
20180424_BZ14_control	- Regions: 1222	Cells: 1215	Genes: 166
20180419_BZ9_control	- Regions: 1385	Cells: 1380	Genes: 166
20180417_BZ5_control	- Regions: 1130	Cells: 1127	Genes: 166
20180505_BY3_1kgenes	- Regions: 1550	Cells: 1549	Genes: 1020
20180410-BY3_1kgenes	- Regions: 974	Cells: 973	Genes: 1020
```

It seems some of the regions should be discarded, but I have no way of knowing which ones?

Looking through your code here, there doesn't seem to be any code that e.g. plots a given genes expression at spatial coordinates?

Best
/Valentine

**Comment by weallen** [comment]
Hi Valentine,

Good catch -- yes, I applied some size filtering of the cells (keeping only cells with < 100,000 and >10,000 pixels) in reads_to_cells.py. (https://github.com/weallen/STARmap/blob/master/python/reads_to_cells.py). I've updated the function GetQHulls in viz.py (https://github.com/weallen/STARmap/blob/master/python/viz.py) to do this; the previous version had the wrong threshold. 

There is also code in that file to plot expression overlaid on the cell segmentation. In general, I only used QHulls to plot the cell segmentation, as it's much faster than working with the raw pixel mask. 

E.g. to plot expression of gene N, try:
```
import matplotlib.pyplot as plt
qhulls,coords = GetQHulls(labels)
n=10
plot_poly_cells_expression(labels, qhulls, counts.iloc[:,n], plt.cm.jet)
```

I don't have any code in Python that plots the individual dots for a gene -- if you write one, I can  incorporate it into the package.

**Comment by vals** [comment]
Hi William,

Thank you for the quick response!

Ok great, with this filtering I consistently get the same number of cells as regions. Perfect.

However, I suspect the ordering in the `cell_barcode_count.csv` is not consistent with the filtered regions.

For me the centroids of the cells are sufficient, so I just plot those, colored by the expression level.

After filtering the regions, I cannot reproduce the Egr1 expression levels in Figure 3A of the paper for the "Light" condition.

```
filtered_regions = []
for i, region in tqdm(enumerate(regionprops(labels))):
    curr_coords = np.argwhere(labels == i)
    if curr_coords.shape[0] < 100000 and curr_coords.shape[0] > 1000:
        filtered_regions.append(region)

centroids = np.array([r.centroid for r in filtered_regions])

figsize(10, 4)
plt.axes().set_aspect('equal', 'datalim');
plt.scatter(-centroids[:, 1], -centroids[:, 0], c=np.log1p(counts['Egr1']));
plt.title('20171115_BF5_light - Egr1');
```
![image](https://user-images.githubusercontent.com/668803/43805602-395f54f2-9a55-11e8-820d-6cb749167a13.png)

Interestingly, for the "Light" condition, I can reproduce Figure 3A by excluding the last region.

```
all_centroids = np.array([r.centroid for r in regionprops(labels)])
figsize(10, 4)
plt.axes().set_aspect('equal', 'datalim');
plt.scatter(-all_centroids[:-1, 1], -all_centroids[:-1, 0], c=np.log1p(counts['Egr1']));
plt.title('20171115_BF5_light - Egr1');
```
![image](https://user-images.githubusercontent.com/668803/43805690-978932be-9a55-11e8-839c-7b468e90a99d.png)

This however did not work for the "Dark" condition, and I'm assuming will not work for the 1000-gene data.

Any ideas?

Best,
/Valentine

**Comment by weallen** [comment]
Hi Valentine,
Yes, I think this is due to a difference between how regionprops works, and how I had been selecting cells using indexing into the array. All of my plotting in the paper was using QHulls selected using indexing directly into the array, and I hadn't properly tested the regionprops code -- my apologies, I'll update the starmapresources website to explain this. I suspect there is an off-by-one error in how regionprops deals with labels==0.  

For now, I would just use the GetQHulls function, and get centroids using the code:
```
qhulls,coords = GetQHulls(labels)
all_centroids  = np.vstack([c.mean(0) for c in coords])
```
E.g. to plot PCP4 (gene index = 102) in the dark 160 gene experiment:

```
plt.figure(figsize=(10, 4))
plt.axes().set_aspect('equal', 'datalim');
plt.scatter(-all_centroids[:, 1], -all_centroids[:, 0], c=np.log1p(counts.iloc[:,102]));
plt.axis('off')

```
![image](https://user-images.githubusercontent.com/526501/43807101-b50eccf8-9a5b-11e8-86eb-56430d98eb07.png)

This worked for me on both the 1000 gene data and 160 gene dark dataset.

- Will

**Comment by vals** [comment]
Thanks Will!

Now I got it working, the GetQHulls function takes a while, but I can of course save the result and re-use.

By the way, I was also wondering something about the large 30K cell dataset: How come the gene counts are so much higher per cell compared to the other datasets?

For example Pcp4 has an average expression of ~10 counts/cell in the 160 gene dataset, but an average expression of ~6,000 counts/cell in the large dataset.

Is the sequential barcoding version of STARmap much more sensitive than the combinatorial barcoding version?

/Valentine

**Comment by weallen** [comment]
Hi Valentine,

I think this was explained in the paper, but the measurements in the sequential mode are not counts but relative intensity measurements within some volume around the cell nucleus. The scaling is somewhat arbitrary. We imaged at low magnification to capture the large volume within a reasonable amount of time, so individual dots were not resolvable. 

Will

**Comment by vals** [comment]
Hi Will,

Oh I see, I didn't catch that when I read it.

That makes sense, those expression levels don't really behave the way counts do. It's cool that it still seems pretty quantitative!

Thanks a lot for your help with these things.

Best
/Valentine
